// <auto-generated />
using System;
using ArtistData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ArtistData.Migrations
{
    [DbContext(typeof(ArtistContext))]
    [Migration("20200819082324_ArtistData")]
    partial class ArtistData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("ArtistData.Models.Artist", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Area")
                        .HasColumnType("int");

                    b.Property<int?>("Begin_area")
                        .HasColumnType("int");

                    b.Property<int?>("Begin_date_day")
                        .HasColumnType("int");

                    b.Property<int?>("Begin_date_month")
                        .HasColumnType("int");

                    b.Property<int?>("Begin_date_year")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Edits_pending")
                        .HasColumnType("int");

                    b.Property<int?>("End_area")
                        .HasColumnType("int");

                    b.Property<int?>("End_date_day")
                        .HasColumnType("int");

                    b.Property<int?>("End_date_month")
                        .HasColumnType("int");

                    b.Property<int?>("End_date_year")
                        .HasColumnType("int");

                    b.Property<bool>("Ended")
                        .HasColumnType("bit");

                    b.Property<int?>("Gender")
                        .HasColumnType("int");

                    b.Property<Guid>("Gid")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("Last_updated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sort_name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Artists");
                });
#pragma warning restore 612, 618
        }
    }
}
